### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Madis0** [henkelmax/server-resourcepack-checker#1]
Is this really ARR with code readable or are you missing the licenses on here and mod platforms?

**Comment by henkelmax** [comment]
Nope, thats completely intended.

**Comment by RaptaG** [comment]
In my opinion having an open source project is really good. Behind the philosophy, it helps on direct contributions & faster bug fixing and there many open source licenses which can protect you and your project.

**Comment by henkelmax** [comment]
Yeah, but what an open source project doesnt "protect" you from is people just reuploading your project on curse and making money off of it.

**Comment by RaptaG** [comment]
> Yeah, but what an open source project doesnt "protect" you from is people just reuploading your project on curse and making money off of it.

Wrong, there are licenses which technically disallow turning a project ARR and/or make money out of it. See [GPL-3.0](https://www.gnu.org/licenses/gpl-3.0.html).
