### ISSUE TITLE
mod doesnt work at all :/

### ISSUE THREAD

**Issue by ghost** [henkelmax/server-resourcepack-checker#2]
I found this mod from Xisumavoid, and i thought it would be very helpful, but when i try to use it, i still get the loading screen when loading into my server and any other server, i do not know y it doesnt work, i rlly would like this mod to work, its a genius idea and i rlly need it lol

**Comment by henkelmax** [comment]
Please fill out the bug template and provide logs.

**Comment by ghost** [comment]
o ok srry! ill just create a new issue
