### ISSUE TITLE
Mod does not work

### ISSUE THREAD

**Issue by ghost** [henkelmax/server-resourcepack-checker#3]
**Bug description**
when i load into my server(that has a rp installed and i have played multiple times) the loading screen still pops up, the mod loads the screen faster but it doesnt completely remove it

**Steps to reproduce the issue**
1. Go to 'a server with a rp ig'
2. Click on 'join'
3. wait, see loading screen
4. See error :p

**Expected behavior**
rp loading screen is not supposed to be there, if i read the mod description correctly

**Log files**
https://gist.github.com/Playz07/50c8a2a51546a9b8b7a841627878e213

**Versions**
- Minecraft version: 1.19.3
- Fabric Loader version: 0.14.14
- Fabric API version: 0.73.2+1.19.3
- Mod version: 1.19.3-1.0.0

**Other mods**
![image](https://user-images.githubusercontent.com/112635249/217720455-4575aaaf-8b5d-4aa8-adb4-895e82ee2189.png)

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Just to make sure. Do you really have the **exact same resource pack** already selected on your client?

**Comment by ghost** [comment]
do you mean in the server resourcepacks file or my resource pack GUI/file?

**Comment by henkelmax** [comment]
Both.

**Comment by ghost** [comment]
I do have it in my server resourcepacks file automatically saved as just a file(I don't know if that is significant) but I do not have it in my GUI, I'm so sorry to waste your time on something so stupid  *facepalm* I will be sure to see if that was my issue once I have a free moment :)

**Comment by ghost** [comment]
That was the issue! I'm so sorry to waste your time on such a silly thing XD, but tysm!!
