### ISSUE TITLE
[suggestion] May I ask if a Forge version can be released?

### ISSUE THREAD

**Issue by luoxiawuchen** [henkelmax/server-resourcepack-checker#4]
Hello author, may I ask if this excellent work plans to release a Forge version? I hope it can also be applied to Forge servers (convenient for players entering Forge servers)

**Comment by henkelmax** [comment]
No, this will be Fabric only, sorry.

**Comment by luoxiawuchen** [comment]
> 

Okay, thank you for your patient response.

**Comment by OffsetMonkey538** [comment]
I can confirm that at least version 1.2.2 for 1.21.1 works on neoforge through sinytra connector
