### ISSUE TITLE
Mod not working in some server

### ISSUE THREAD

**Issue by No-Eul** [henkelmax/server-resourcepack-checker#6]
### Bug description

Some servers provide a resource pack that seems to be using different compression algorithm than used for client resource packs, either to prevent from unzip or for other purpose. To use these resource packs, we should repack to use such as https://javadecompilers.com, not general zipping software. But the repacked one and the provided have a different hash, so the mod not working as intended.

### Minecraft version

1.21.1

### Mod version

1.21.1-1.2.2

### Mod loader and version

Fabric Loader 0.16.2

### Steps to reproduce

1. Download the resource pack from http://pack.wonderland-server.net/20240509.zip
2. Rename to make it end with `.jar`
3. Go https://www.decompiler.com and upload it to repack as a regular zip file
4. If the resource pack structure is in internal directory of the zip file, move or repack the zip to be located under the root
5. Apply the repacked one and join `wonderland-server.net` server.
6. See to be redownloading the resource pack

### Expected behavior

The server resource pack is not downloading again.

### Log files

There's no error log messages

**Comment by henkelmax** [comment]
The hashes of the zip file need to exactly match. If you change the compression type, it obviously will not have the same hash anymore.
